---
new_page_extension: md
auto_deploy: true
admin_path: ''
webhook_url: 
sections:
- type: document
  path: paperview.md
  label: Paperview
  match: "**/*"
  read_only: false
- type: heading
  label: Content
- type: directory
  path: _bishop
  label: Bishop
  create: all
  match: "**/*"
  templates:
  - bishop_tmp
- type: directory
  path: _paper
  label: Paper
  create: all
  match: "**/*"
  templates:
  - paper_tmp
- type: jekyll-posts
  label: Posts
  create: all
  templates:
  - post
- type: jekyll-pages
  label: Pages
  create: all
  templates:
  - landing-page
  - page
- type: document
  path: _data/information.yml
  label: Contact Information
upload_dir: uploads
public_path: "/uploads"
front_matter_path: ''
use_front_matter_path: false
file_template: ":year:/:month:/:day:/:filename:"
instant_preview: true
build:
  preview_command: bundle exec jekyll build --drafts --unpublished --future -d _site
  publish_command: bundle exec jekyll build -d _site
  preview_env:
  - JEKYLL_ENV=staging
  publish_env:
  - JEKYLL_ENV=production
  preview_output_directory: _site
  output_directory: _site
  instant_preview_command: bundle exec jekyll serve --drafts --unpublished --future
    --port 8080 --host 0.0.0.0 -d _site
  preview_docker_image: forestryio/ruby:2.6
  mount_path: "/srv"
